# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bai1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MangMayTinh(object):
    def setupUi(self, MangMayTinh):
        MangMayTinh.setObjectName("MangMayTinh")
        MangMayTinh.resize(334, 231)
        MangMayTinh.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(MangMayTinh)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_login = QtWidgets.QToolButton(self.centralwidget)
        self.Button_login.setGeometry(QtCore.QRect(30, 40, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Button_login.setFont(font)
        self.Button_login.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.Button_login.setObjectName("Button_login")
        self.button_register = QtWidgets.QToolButton(self.centralwidget)
        self.button_register.setGeometry(QtCore.QRect(30, 130, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.button_register.setFont(font)
        self.button_register.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.button_register.setObjectName("button_register")
        MangMayTinh.setCentralWidget(self.centralwidget)

        self.retranslateUi(MangMayTinh)
        QtCore.QMetaObject.connectSlotsByName(MangMayTinh)

    def retranslateUi(self, MangMayTinh):
        _translate = QtCore.QCoreApplication.translate
        MangMayTinh.setWindowTitle(_translate("MangMayTinh", "MainWindow"))
        self.Button_login.setText(_translate("MangMayTinh", "Login"))
        self.button_register.setText(_translate("MangMayTinh", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MangMayTinh = QtWidgets.QMainWindow()
    ui = Ui_MangMayTinh()
    ui.setupUi(MangMayTinh)
    MangMayTinh.show()
    sys.exit(app.exec_())
