# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bai3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(488, 309)
        self.centralwidget = QtWidgets.QWidget(Register)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 491, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.text_user = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_user.setGeometry(QtCore.QRect(170, 120, 271, 31))
        self.text_user.setObjectName("text_user")
        self.text_pass = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_pass.setGeometry(QtCore.QRect(170, 170, 271, 31))
        self.text_pass.setObjectName("text_pass")
        self.button_signup_2 = QtWidgets.QToolButton(self.centralwidget)
        self.button_signup_2.setGeometry(QtCore.QRect(210, 220, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_signup_2.setFont(font)
        self.button_signup_2.setObjectName("button_signup_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.button_signup = QtWidgets.QToolButton(self.centralwidget)
        self.button_signup.setGeometry(QtCore.QRect(300, 270, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.button_signup.setFont(font)
        self.button_signup.setObjectName("button_signup")
        Register.setCentralWidget(self.centralwidget)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "MainWindow"))
        self.label.setText(_translate("Register", "<html><head/><body><p align=\"center\">Register</p></body></html>"))
        self.label_2.setText(_translate("Register", "<html><head/><body><p>Username</p></body></html>"))
        self.label_3.setText(_translate("Register", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Password</span></p></body></html>"))
        self.button_signup_2.setText(_translate("Register", "Sign Up"))
        self.label_4.setText(_translate("Register", "If you have an account, sign up here"))
        self.button_signup.setText(_translate("Register", "Sign in"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register = QtWidgets.QMainWindow()
    ui = Ui_Register()
    ui.setupUi(Register)
    Register.show()
    sys.exit(app.exec_())
