# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bai6.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_2(object):
    def setupUi(self, delete_2):
        delete_2.setObjectName("delete_2")
        delete_2.resize(375, 110)
        self.centralwidget = QtWidgets.QWidget(delete_2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(212, 255, 111);")
        self.label.setObjectName("label")
        self.filetext = QtWidgets.QLineEdit(self.centralwidget)
        self.filetext.setGeometry(QtCore.QRect(0, 60, 381, 51))
        self.filetext.setObjectName("filetext")
        delete_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(delete_2)
        QtCore.QMetaObject.connectSlotsByName(delete_2)

    def retranslateUi(self, delete_2):
        _translate = QtCore.QCoreApplication.translate
        delete_2.setWindowTitle(_translate("delete_2", "MainWindow"))
        self.label.setText(_translate("delete_2", "<html><head/><body><p align=\"center\">Đã xóa file</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delete_2 = QtWidgets.QMainWindow()
    ui = Ui_delete_2()
    ui.setupUi(delete_2)
    delete_2.show()
    sys.exit(app.exec_())
